### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/everything#1]
I'll work on the TLC logo and members can provide feedback.

**Comment by yelluw** [comment]
I dont have any design software installed in the machine I'm on right now. I still managed to do a little tinkering and came up with this:

![tlc-logo](https://cloud.githubusercontent.com/assets/23017027/26421863/98ecea62-4095-11e7-861e-a3b6139e6604.PNG)

This is not the final logo. I'm trying to get a feel for it. Inspiration comes from the old wild west wanted posters.

**Comment by bizmonger** [comment]
Missing the Lambda operator...

**Comment by yelluw** [comment]
Yes, totally. It's going in there for sure. Just trying to figure out if we want it to look rough or more modern.

**Comment by bizmonger** [comment]
Rough just like the current logo

**Comment by yelluw** [comment]
Posting this from the Twitter dm thread

https://www.meetup.com/Lambda-Lounge-Krakow/photos/13141152/204742162/

Ill combine both.

**Comment by yelluw** [comment]
@bizmonger 

![logo](https://cloud.githubusercontent.com/assets/23017027/26428244/a318e09a-40ae-11e7-8a48-2a33f83bab63.png)

I like this one 💯

**Comment by yelluw** [comment]
This would be the icon:

![icon](https://cloud.githubusercontent.com/assets/23017027/26428426/99758bc8-40af-11e7-92b8-a72c269af7e5.png)

**Comment by awright18** [comment]
That looks great!

**Comment by bizmonger** [comment]
Nice




Get Outlook for Android







On Wed, May 24, 2017 at 8:47 PM -0400, "Adam Wright" <notifications@github.com> wrote:












That looks great!

**Comment by yelluw** [comment]
Ok then these are it then.

The icon for profile pics.

The full logo for everything else.
