### ISSUE TITLE
Podcast audio leveling up? 

### ISSUE THREAD

**Issue by awright18** [Lambda-Cartel/everything#17]
@marukami had mentioned recording our own audio and stitching it together. I think that could be easily done with a number of tools, but I think @marukami might have some suggestions.  I'd love to hear some from him.  Also this would probably require some kind of sharing via a cloud drive of some sort, like google cloud drive, dropbox, onedrive etc. That is probably something to think about anyway.

**Comment by marukami** [comment]
The Shop Talk Show had a good [episode on podcasting](https://dev.to/shoptalkshow/265-on-podcasting). 

The main idea is that each attendee records their microphone separately. Then collect all the audio files and stitch them tougher; stitch can be a bit tricky depending on the software. I've got Adobe Audition for editing and Audition can automatically sync tracks. 

For Recording the simplest way on Windows might be `Voice Recorder` and `QuickTime` on MacOS. 

I made a Google [drive folder](https://drive.google.com/drive/folders/0B8phGUR36tcZQlBxcDA2c3Q4Wm8?usp=sharing) we can try that.

**Comment by yelluw** [comment]
This is not a bad idea. The current process is a bit rough. However, Im worried that increasing the quality of the podcast might decrease time available for writing code. What do you think?

**Comment by bizmonger** [comment]
I agree with Pablo.

**Comment by marukami** [comment]
Having reasonable microphones might be enough for the way we are doing
things now.

I can edit and compose the audio tracks fairly quickly. If someone can't or
does not record the audio you can use the hangout steam audio.

**Comment by yelluw** [comment]
@marukami 

Thats great. I have the snowball ice mic. So that will work well. How would we go about recording it separately?

**Comment by yelluw** [comment]
Never mind. Re-read your previous comment. Ill try it out and report back. :)

**Comment by awright18** [comment]
Audacity is also a free option if you need want anything more than just a
record and stop you could also use http://www.audacityteam.org/  but that
may be overkill.

**Comment by awright18** [comment]
https://zencastr.com/
