### ISSUE TITLE
Please make me an admin to update the org settings

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/everything#2]
I want to update a couple of things and need to have admin access. :)

**Comment by yelluw** [comment]
@bizmonger Could you do so, please? Id like to update the profile pic.

**Comment by bizmonger** [comment]
At the bar now.


I'll try to later tonight.




Apologies.




Get Outlook for Android







On Thu, May 25, 2017 at 7:09 PM -0400, "Pablo Rivera" <notifications@github.com> wrote:












@bizmonger Could you do so, please? Id like to update the profile pic.
