### ISSUE TITLE
Youtube video structure and details

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/everything#5]
I realized that the Youtube videos can be converted into audio and re-published as a podcast. Not all of the videos will be fit for that, but we can leverage this to reach more people with our content.

That means that there are two types of videos:

1. Videos that do not feature visual content.

2. Videos that feature visual content. Things like slides, images, live coding, etc.

Both videos require a certain amount of structure. This helps people know what to expect from it. Things like subject, duration, etc are important. I feel we should follow this structure:

- Short standard intro:

**This is The Lambda Cartel. I'm `$name` and `$name` is here with me.
Today we will be talking about $subject.**

- Standard duration. We should aim for intervals of 7 minutes. Why 7? Because it people tend to consume content in multiples of 7. Its not seen as too long or too short. A 7 minute piece of content has roughly the same amount of info as a 10 minute one. Same for 14, 21, 28, etc.

This requires us to think about the subject beforehand. Might prove challenging at first, but will benefit all. Having a standard time format means we can schedule our videos better and more people will tune in.

- Content guidelines. Let's keep the content clean with no bad words or foul language. 

Suggestions? Opinions?

@bizmonger @awright18 @BryanWilhite 

(Ody is missing from github?)

**Comment by BryanWilhite** [comment]
no objections here

btw: Ody is here: https://github.com/odytrice

**Comment by bizmonger** [comment]
YouTube channel with Live feature is now enabled.

**Comment by awright18** [comment]
Sounds like a good idea

**Comment by yelluw** [comment]
This info seems to better fit a wiki page. Ill move it over.

**Comment by yelluw** [comment]
Moved to a wiki page https://github.com/Lambda-Cartel/everything/wiki/Youtube-videos-content-structure-and-guidelines
