### ISSUE TITLE
Create a simple project charter

### ISSUE THREAD

**Issue by awright18** [Lambda-Cartel/everything#7]
I think it would be nice to have something in writing somewhere that states the goals, rules, and things of that nature so we as the Cartel understand why we are here, what we are working towards, etc.  I think I have an idea, but its vague at the moment.  This can and probably should be very high level.

**Comment by yelluw** [comment]
Go ahead and post anything you have in mind. I'm working on something in the same vein. Would love to see hat you come up with. @awright18

**Comment by awright18** [comment]
I added this to the everything wiki. Its is a very rough draft and will require people to add some short bios.  https://github.com/Lambda-Cartel/everything/wiki/Lambda-Cartel-Charter

**Comment by yelluw** [comment]
Great work, @awright18 I'm going through other issues at the moment and will get to it soon. :+1:

**Comment by yelluw** [comment]
@odytrice @marukami @BryanWilhite  I need for each of you to provide a short bio. I'm using it for the website. Add it it here or to the charter and let me know when you do. :)

**Comment by marukami** [comment]
This is the one I normally use. 
```
Mitchell Tilbrook is a freelance mobile developer focused on Android and React-Native development in Sydney. Mitchell has developed mobile apps for both native iOS, Android, Xamarin, and React. Mithcell is an organizer for F# Sydney, Kotlin Sydney, and Xamarin meetups. Mitchell is also helping bring Sydney's tech scene to the world by recording and uploads amazing talks for Android, React Native, Alt.NET, SydJs and other local meetups. His favorite paradigm is functional. 
```

**Comment by yelluw** [comment]
Ok, Ive added the profiles for each member. Thanks all. :)
