### ISSUE TITLE
Determine and Purchase a domain name.

### ISSUE THREAD

**Issue by awright18** [Lambda-Cartel/everything#8]
This should probably be done soon.  I don't mind doing it, I use dnsimple.com, and can share management of the domain with any or all of the founding members.  The simplest and most obvious domains are LambdaCartel.org or LambdaCartel.com, but we could probably be fancy and have a lambdacartel.io or something. I honestly don't care.  If @bizmonger wants to take ownership of this that's perfectly fine by me.   This is probably something that should be done soon.

**Comment by bizmonger** [comment]
Sounds good...
 But I rather not manage that aspect (i.e. domain registration).
  
  
  

----------------------------------------

**Comment by yelluw** [comment]
I'll add it to my namecheap account. No worries.

**Comment by yelluw** [comment]
This was already purchased by another member. 
Closing issue.
