### ISSUE TITLE
Create a public calendar

### ISSUE THREAD

**Issue by awright18** [Lambda-Cartel/everything#9]
I think @yelluw is going to tackle this one. We could at the very least put our daily work schedules on there so we know when we probably don't have time to communicate.   Like @yelluw mentioned on the original kickoff we have a lot of different time zones to deal with, and I can be available any time as long as a I have a little notice.

**Comment by yelluw** [comment]
I'm creating a google / email account and that includes access to google calendar. We can use it (its pretty good).

**Comment by yelluw** [comment]
Use the url below to view the calendar. I can give you access. Email me or let me know and I'll add events. :)

https://calendar.google.com/calendar/embed?src=lambdacartel%40gmail.com&ctz=Atlantic/Azores
